version: "3.9"


services:
  app:
    build:
      context: .
    ports:
      - "8080:80"
    volumes:
      - ./data:/project/data
    depends_on:
      migrations:
        condition: service_completed_successfully
  migrations:
    build:
      context: .
    volumes:
      - ./data:/project/data
    command: ls -la