  name: Build action number one
  on: [push]
  jobs:
    build_and_push:
      runs-on: ubuntu-20.04
      steps:
        - name: debug one
          run: ls -la
        - name: clone code
          uses: actions/checkout@v2
        - name: debug 2
          run: ls -l